### ISSUE TITLE
Add new category: Activity

### ISSUE THREAD

**Issue by anastasia77705** [UNICEFECAR/parent-buddy-cms#14]
Add the following category in Categories taxonomy:

- Activity

**Comment by juricababic** [comment]
@anastasia77705 Given that we are creating a dedicated content type for Activities, it perhaps makes no sense to add a category named "Activity". What do you think? If you agree, I propose that we close this issue for the time being and focus on: https://github.com/UNICEFECAR/parent-buddy-cms/issues/15

**Comment by anastasia77705** [comment]
@juricababic  I agree
