### ISSUE TITLE
Add new content type called Activity 

### ISSUE THREAD

**Issue by anastasia77705** [UNICEFECAR/parent-buddy-cms#15]
https://docs.google.com/document/d/1ddB34lM9shV_f6BKd9e6N_fRXhL5jW307YqDupQh53o/edit?usp=sharing

**Comment by juricababic** [comment]
@anastasia77705 - as mentioned on Github, given that Activity is a dedicated content type, it makes no sense to flag them as "Activity" category. Therefore, I propose we remove "category" field from it. I made the same note in the provided Google spreadsheet.

Is this fine with you?

**Comment by juricababic** [comment]
@anastasia77705 - and yes, we will need API for it but not at this moment so please put that part (API development) in the backlog.

**Comment by anastasia77705** [comment]
@juricababic Done and agreed regarding API

**Comment by dragomir-pantelic** [comment]
Finished creating new Content Type. Need to determine who gets access to this Content Type so that proper permissions/roles can be assigned.
